import os

path = os.path.join("src", "rag", "pipeline.py")

lines = [
    "import sys",
    "import os",
    "from pathlib import Path",
    "sys.path.append(str(Path(__file__).parent.parent.parent))",
    "sys.stdout.reconfigure(encoding='utf-8', errors='replace')",
    "",
    "from langchain_openai import ChatOpenAI",
    "from langchain_core.messages import HumanMessage",
    "from src.knowledge_base.vectorstore import VectorStoreManager",
    "from src.memory.session_memory import SessionMemoryManager",
    "from config.settings import OPENAI_API_KEY, LLM_MODEL, LLM_TEMPERATURE, TOP_K_RESULTS",
    "",
    "",
    'SYSTEM_PROMPT = """You are SmartServe AI, a professional customer support assistant.',
    "You help customers with product issues, technical problems, orders, and general queries.",
    "",
    "STRICT RULES:",
    "1. Always prioritize the context provided below when answering.",
    "2. If the context is partial or unclear, combine it with general best-practice",
    "   troubleshooting knowledge to give a helpful response.",
    "   Only say you cannot help if the topic is completely outside support scope.",
    "3. Use the conversation history to maintain context across messages.",
    "   Reference previous messages when relevant.",
    "4. Be professional, empathetic, and concise. Max 150 words per response.",
    "5. If the customer seems frustrated, acknowledge their frustration first.",
    "6. Always end your response with: 'Is there anything else I can help you with?'",
    "7. For order-specific queries, ask for the customer's Order ID if not provided.",
    "8. Never reveal that you are using a knowledge base or retrieved documents.",
    "",
    "CONVERSATION HISTORY (last 5 turns):",
    "{chat_history}",
    "",
    "CONTEXT FROM KNOWLEDGE BASE:",
    "{context}",
    "",
    "CUSTOMER QUESTION:",
    "{question}",
    "",
    'YOUR RESPONSE:"""',
    "",
    "",
    "class RAGPipeline:",
    '    """Memory-aware RAG pipeline with per-session conversation history."""',
    "",
    "    def __init__(self):",
    '        print("[RAG] Initializing RAG Pipeline with Memory...")',
    "        self.vs_manager = VectorStoreManager()",
    "        self.vectorstore = self.vs_manager.load_vectorstore()",
    "        self.retriever = self.vectorstore.as_retriever(",
    '            search_type="similarity",',
    '            search_kwargs={"k": TOP_K_RESULTS}',
    "        )",
    "        self.llm = ChatOpenAI(",
    "            model=LLM_MODEL,",
    "            temperature=LLM_TEMPERATURE,",
    "            openai_api_key=OPENAI_API_KEY",
    "        )",
    "        self.memory_manager = SessionMemoryManager(window_size=5)",
    '        print("[RAG] Pipeline with memory ready!")',
    "",
    "    def _format_docs(self, docs: list) -> str:",
    "        formatted = []",
    "        for i, doc in enumerate(docs, 1):",
    "            source   = doc.metadata.get('source', 'knowledge_base')",
    "            category = doc.metadata.get('category', '')",
    "            product  = doc.metadata.get('product', '')",
    "            label_parts = [f'Source {i}', source]",
    "            if product and product != 'N/A':",
    "                label_parts.append(f'Product: {product}')",
    "            if category:",
    "                label_parts.append(f'Category: {category}')",
    "            formatted.append(f\"[{' | '.join(label_parts)}]\\n{doc.page_content}\")",
    '        return "\\n\\n---\\n\\n".join(formatted)',
    "",
    "    def get_answer(self, question: str, session_id: str = 'default') -> dict:",
    "        if not question or not question.strip():",
    "            return {",
    '                "answer": "I did not receive a question. Could you please rephrase?",',
    '                "sources": [], "confidence": "low", "chunks": []',
    "            }",
    "        source_docs = self.retriever.invoke(question)",
    "        context = self._format_docs(source_docs)",
    "        chat_history = self.memory_manager.get_history_as_text(session_id)",
    "        prompt_text = SYSTEM_PROMPT.format(",
    "            chat_history=chat_history if chat_history else 'No previous messages.',",
    "            context=context,",
    "            question=question",
    "        )",
    "        response = self.llm.invoke([HumanMessage(content=prompt_text)])",
    "        answer = response.content",
    "        self.memory_manager.save_turn(session_id, question, answer)",
    "        sources = list(set(",
    "            doc.metadata.get('source', 'N/A') for doc in source_docs",
    "        ))",
    "        if len(source_docs) >= 3:",
    '            confidence = "high"',
    "        elif len(source_docs) >= 2:",
    '            confidence = "medium"',
    "        else:",
    '            confidence = "low"',
    "        return {",
    '            "answer":     answer,',
    '            "sources":    sources,',
    '            "confidence": confidence,',
    '            "chunks":     [doc.page_content[:100] for doc in source_docs],',
    '            "turn_count": self.memory_manager.turn_count(session_id)',
    "        }",
    "",
    "    def clear_session(self, session_id: str):",
    "        self.memory_manager.clear_session(session_id)",
    "",
    "    def test_pipeline(self):",
    "        session = 'test_memory_session'",
    '        print("\\n" + "=" * 60)',
    '        print("  RAG PIPELINE TEST -- Memory & Follow-up")',
    '        print("=" * 60)',
    "        questions = [",
    "            ('Q1 -- Initial query',",
    "             'My laptop screen is flickering'),",
    "            ('Q2 -- Follow-up (needs memory)',",
    "             'What if those steps do not work?'),",
    "            ('Q3 -- New topic',",
    "             'How do I cancel my order?')",
    "        ]",
    "        for label, question in questions:",
    "            print(f'\\n[{label}]')",
    "            print(f'Customer: {question}')",
    '            print("-" * 60)',
    "            result = self.get_answer(question, session_id=session)",
    "            print(f\"Turn     : {result['turn_count']}\")",
    "            print(f\"Sources  : {result['sources']}\")",
    "            print(f\"Answer   :\\n{result['answer']}\")",
    '            print("=" * 60)',
]

content = "\n".join(lines) + "\n"

with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"[OK] Written: {path}")
print(f"[OK] Lines  : {len(lines)}")

checks = ["class RAGPipeline", "def get_answer", "def test_pipeline",
          "SessionMemoryManager", "chat_history", "turn_count", "save_turn"]
print("\nContent check:")
for c in checks:
    status = "[OK]" if c in content else "[MISSING]"
    print(f"  {status}  {c}")